apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: echo-service
  namespace: knative-demo
spec:
  template:
    metadata:
      name: echo-service-v7
    spec:
      containers:
      - image: docker.io/axodevelopment/echo-service:v0.1.0
        ports:
        - containerPort: 8080
        env:
        - name: UKEY
          value: "VERSION-7"
